import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nadia Gincoff ⬥ Web Developer',
  description: 'Generated by Nadia Gincoff',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const date = new Date().getFullYear()

  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className={`${inter.className}`}>
          {children} 
      </body>
    </html>
  )
}